### ISSUE TITLE
这个是hyperf对接dubbo的rpc的吗?大佬 还更新这个repo吗 . 

### ISSUE THREAD

**Issue by jonny77** [myziyue/dubbo-client-php#1]

**Comment by evan2884** [comment]
这项目本来是公司内部用来hyperf项目对接dubbo的rpc，和Java团队无缝衔接的，但是后来公司内部原因没有用上的。暂时不考虑更新了，谢谢你的关注哈

**Comment by jonny77** [comment]
> 这项目本来是公司内部用来hyperf项目对接dubbo的rpc，和Java团队无缝衔接的，但是后来公司内部原因没有用上的。暂时不考虑更新了，谢谢你的关注哈

后来改成什么方案了?

**Comment by evan2884** [comment]
> 

grpc/json-rpc + mq 的方案，后面公司架构调整，很多事情都没进行下去了
